language: go
go:
  - 1.11
  - tip
sudo: false
install:
  - go get github.com/ThomasHabets/drive-du/lib
  - go get github.com/golang/glog
  - go get github.com/rthornton128/goncurses
  - go get golang.org/x/oauth2
  - go get google.golang.org/api/gmail/v1
  - go get golang.org/x/text/encoding
  - go get github.com/mattn/go-runewidth
  - go get github.com/pkg/errors
  - go get github.com/sirupsen/logrus
  - go get golang.org/x/crypto/ssh/terminal
